CREATE TABLE IF NOT EXISTS NOTE (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    TITLE VARCHAR(255) NOT NULL,
    CONTENT TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS GOAT (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    BREED VARCHAR(255) NOT NULL
);

